// Static demo asset manifest.

export type WorkoutAsset = { file: string; title: string; mod: number };

export const WORKOUT_ASSETS: WorkoutAsset[] = [
  { file: "WF-BIKE-B30.html", title: "WF-BIKE-B30", mod: require("./assets/workouts/WF-BIKE-B30.html") },
  { file: "WF-BIKE-B40.html", title: "WF-BIKE-B40", mod: require("./assets/workouts/WF-BIKE-B40.html") },
  { file: "WF-BIKE-I30.html", title: "WF-BIKE-I30", mod: require("./assets/workouts/WF-BIKE-I30.html") },
  { file: "WF-BIKE-T25.html", title: "WF-BIKE-T25", mod: require("./assets/workouts/WF-BIKE-T25.html") },
  { file: "WF-CARD-B30.html", title: "WF-CARD-B30", mod: require("./assets/workouts/WF-CARD-B30.html") },
  { file: "WF-CARD-B40.html", title: "WF-CARD-B40", mod: require("./assets/workouts/WF-CARD-B40.html") },
  { file: "WF-CARD-I30.html", title: "WF-CARD-I30", mod: require("./assets/workouts/WF-CARD-I30.html") },
  { file: "WF-CARD-T25.html", title: "WF-CARD-T25", mod: require("./assets/workouts/WF-CARD-T25.html") },
  { file: "WF-CARDIO20.html", title: "WF-CARDIO20", mod: require("./assets/workouts/WF-CARDIO20.html") },
  { file: "WF-CORE-10.html", title: "WF-CORE-10", mod: require("./assets/workouts/WF-CORE-10.html") },
  { file: "WF-CORE-HANG10.html", title: "WF-CORE-HANG10", mod: require("./assets/workouts/WF-CORE-HANG10.html") },
  { file: "WF-CORE-ONLY8.html", title: "WF-CORE-ONLY8", mod: require("./assets/workouts/WF-CORE-ONLY8.html") },
  { file: "WF-DB-ARMS15.html", title: "WF-DB-ARMS15", mod: require("./assets/workouts/WF-DB-ARMS15.html") },
  { file: "WF-DB-LEGS20.html", title: "WF-DB-LEGS20", mod: require("./assets/workouts/WF-DB-LEGS20.html") },
  { file: "WF-DB-PULL20.html", title: "WF-DB-PULL20", mod: require("./assets/workouts/WF-DB-PULL20.html") },
  { file: "WF-DB-SHOULDER15.html", title: "WF-DB-SHOULDER15", mod: require("./assets/workouts/WF-DB-SHOULDER15.html") },
  { file: "WF-DELOAD.html", title: "WF-DELOAD", mod: require("./assets/workouts/WF-DELOAD.html") },
  { file: "WF-FLOW-15.html", title: "WF-FLOW-15", mod: require("./assets/workouts/WF-FLOW-15.html") },
  { file: "WF-ILL-RB50.html", title: "WF-ILL-RB50", mod: require("./assets/workouts/WF-ILL-RB50.html") },
  { file: "WF-ILL-RB75.html", title: "WF-ILL-RB75", mod: require("./assets/workouts/WF-ILL-RB75.html") },
  { file: "WF-ILL-T1.html", title: "WF-ILL-T1", mod: require("./assets/workouts/WF-ILL-T1.html") },
  { file: "WF-ILL-T2.html", title: "WF-ILL-T2", mod: require("./assets/workouts/WF-ILL-T2.html") },
  { file: "WF-MB-12.html", title: "WF-MB-12", mod: require("./assets/workouts/WF-MB-12.html") },
  { file: "WF-MOVE-10.html", title: "WF-MOVE-10", mod: require("./assets/workouts/WF-MOVE-10.html") },
  { file: "WF-NECK-8.html", title: "WF-NECK-8", mod: require("./assets/workouts/WF-NECK-8.html") },
  { file: "WF-OFF-AM15.html", title: "WF-OFF-AM15", mod: require("./assets/workouts/WF-OFF-AM15.html") },
  { file: "WF-OFF-AM20.html", title: "WF-OFF-AM20", mod: require("./assets/workouts/WF-OFF-AM20.html") },
  { file: "WF-PARA-TECH10.html", title: "WF-PARA-TECH10", mod: require("./assets/workouts/WF-PARA-TECH10.html") },
  { file: "WF-PULL-MICRO5.html", title: "WF-PULL-MICRO5", mod: require("./assets/workouts/WF-PULL-MICRO5.html") },
  { file: "WF-PULL-MICRO8.html", title: "WF-PULL-MICRO8", mod: require("./assets/workouts/WF-PULL-MICRO8.html") },
  { file: "WF-REC-15.html", title: "WF-REC-15", mod: require("./assets/workouts/WF-REC-15.html") },
  { file: "WF-SBX-10.html", title: "WF-SBX-10", mod: require("./assets/workouts/WF-SBX-10.html") },
  { file: "WF-STR-A2.html", title: "WF-STR-A2", mod: require("./assets/workouts/WF-STR-A2.html") },
  { file: "WF-STR-A25.html", title: "WF-STR-A25", mod: require("./assets/workouts/WF-STR-A25.html") },
  { file: "WF-STR-A3.html", title: "WF-STR-A3", mod: require("./assets/workouts/WF-STR-A3.html") },
  { file: "WF-STR-B2.html", title: "WF-STR-B2", mod: require("./assets/workouts/WF-STR-B2.html") },
  { file: "WF-STR-B25.html", title: "WF-STR-B25", mod: require("./assets/workouts/WF-STR-B25.html") },
  { file: "WF-STR-B3.html", title: "WF-STR-B3", mod: require("./assets/workouts/WF-STR-B3.html") },
  { file: "WF-STR-C2.html", title: "WF-STR-C2", mod: require("./assets/workouts/WF-STR-C2.html") },
  { file: "WF-STR-C25.html", title: "WF-STR-C25", mod: require("./assets/workouts/WF-STR-C25.html") },
  { file: "WF-STRETCH-20.html", title: "WF-STRETCH-20", mod: require("./assets/workouts/WF-STRETCH-20.html") },
  { file: "WF-UPPER12.html", title: "WF-UPPER12", mod: require("./assets/workouts/WF-UPPER12.html") },
];
